// gen_codegen_tests — build-time generator. Reads the L1 test
// corpus (test_cases.cpp) and emits one recompiled C function per
// case into generated/test_funcs.cpp, alongside the kTestFns lookup
// table. The runner then links the result and runs each function.
//
// Usage:  gen_codegen_tests <output.cpp>
//
// The emitted file is a normal translation unit that:
//   - #includes runtime_arm.h (g_cpu, bus_*, arm_*)
//   - declares one `static void tc_<idx>(void)` per case
//   - defines them with bodies produced by ArmCodegen::emit_instr
//   - exposes `const TestFn kTestFns[]` + `const unsigned kTestFnsCount`
//
// Per PRINCIPLES.md "Interpreter is informative, never load-bearing":
// the generator never calls the interpreter. It calls ArmCodegen
// directly, the same way tools/gba_recompile does.

#include "test_cases.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "arm_codegen.h"
#include "arm_decode.h"
#include "arm_ir.h"
#include "thumb_decode.h"

namespace {

armv4t::Instr decode_one(const TestCase& tc) {
    if (tc.thumb) {
        return armv4t::ThumbDecoder::decode(
            static_cast<uint16_t>(tc.word & 0xFFFFu), tc.pc);
    }
    return armv4t::ArmDecoder::decode(tc.word, tc.pc);
}

int emit(FILE* f, const char* out_path) {
    const std::unordered_set<uint32_t> thumb_alu_immediate_override_pcs = {
        0x0800E2D2u,
        0x0800E31Cu,
        0x080B291Cu,
    };
    std::size_t guarded_trace_sites = 0;
    std::size_t tail_transfer_sites = 0;
    std::fprintf(f,
        "// generated by gen_codegen_tests — DO NOT EDIT.\n"
        "//\n"
        "// One C function per L1 test case. Each body is what\n"
        "// ArmCodegen::emit_instr produced for that case's decoded\n"
        "// IR. The runner invokes these alongside Interpreter::step\n"
        "// and diffs the resulting state.\n"
        "\n"
        "#include \"runtime_arm.h\"\n"
        "#include \"test_cases.h\"\n"
        "\n"
        "// Reached only when the instruction falls through to the next one.\n"
        "// A tail transfer (GBARECOMP_TAIL_*) must return before it; the\n"
        "// runner checks this against whether a transfer was dispatched.\n"
        "extern \"C\" void codegen_test_fellthrough(void);\n"
        "\n");

    // Per-test function bodies.
    for (std::size_t i = 0; i < kTestCasesCount; ++i) {
        const TestCase& tc = kTestCases[i];
        armv4t::Instr ins = decode_one(tc);
        armv4t::CodegenCtx ctx{};
        ctx.current_function_addr = tc.pc;
        ctx.alu_immediate_override_pcs =
            &thumb_alu_immediate_override_pcs;
        bool not_implemented = false;
        std::string body = armv4t::ArmCodegen::emit_instr(
            ins, ctx, &not_implemented);
        for (std::size_t trace_pos = body.find("runtime_trace_event(");
             trace_pos != std::string::npos;
             trace_pos = body.find("runtime_trace_event(",
                                   trace_pos + std::strlen("runtime_trace_event("))) {
            const std::size_t line_start = body.rfind('\n', trace_pos);
            const std::size_t guard_start =
                (line_start == std::string::npos) ? 0u : line_start + 1u;
            const std::string prefix =
                body.substr(guard_start, trace_pos - guard_start);
            if (prefix.find("if (runtime_trace_enabled())") ==
                std::string::npos) {
                std::fprintf(stderr,
                    "gen_codegen_tests: ERROR — case %zu (%s) emits a "
                    "runtime_trace_event call without a same-line "
                    "runtime_trace_enabled guard.\n",
                    i, tc.name);
                return 4;
            }
            ++guarded_trace_sites;
        }

        // Guaranteed tail transfers (runtime_arm.h GBARECOMP_TAIL_*) expand to
        // TWO statements natively (`call; return`). They are only safe as a
        // complete statement on its own line inside a braced block; an
        // unbraced `if (c) GBARECOMP_TAIL_...;` would return unconditionally.
        for (std::size_t tail_pos = body.find("GBARECOMP_TAIL_");
             tail_pos != std::string::npos;
             tail_pos = body.find("GBARECOMP_TAIL_",
                                  tail_pos + std::strlen("GBARECOMP_TAIL_"))) {
            const std::size_t line_start = body.rfind('\n', tail_pos);
            const std::size_t first =
                (line_start == std::string::npos) ? 0u : line_start + 1u;
            std::size_t line_end = body.find('\n', tail_pos);
            if (line_end == std::string::npos) line_end = body.size();
            const std::string prefix = body.substr(first, tail_pos - first);
            const std::string line = body.substr(first, line_end - first);
            if (prefix.find_first_not_of(" \t") != std::string::npos ||
                line.empty() || line.back() != ';') {
                std::fprintf(stderr,
                    "gen_codegen_tests: ERROR — case %zu (%s) emits a "
                    "GBARECOMP_TAIL_* transfer that is not a whole statement "
                    "on its own line: %s\n",
                    i, tc.name, line.c_str());
                return 6;
            }
            ++tail_transfer_sites;
        }

        std::fprintf(f,
            "// [%zu] %s (%s) pc=0x%08X word=0x%08X%s\n"
            "extern \"C\" void tc_%zu(void) {\n"
            "%s"
            "    codegen_test_fellthrough();\n"
            "}\n\n",
            i, tc.name, tc.thumb ? "THUMB" : "ARM",
            tc.pc, tc.word,
            not_implemented ? "  <not implemented!>" : "",
            i, body.c_str());

        if (not_implemented) {
            std::fprintf(stderr,
                "gen_codegen_tests: WARNING — case %zu (%s) decoded to "
                "an unimplemented IrOp shape. The runner will abort on "
                "runtime_unimplemented_op when this test runs.\n",
                i, tc.name);
        }
    }

    // Named-target variants: the same instruction with its static branch
    // target resolved to a function name, which is how real games reach
    // GBARECOMP_TAIL_CALL (B) and named BL calls.
    std::fprintf(f, "extern \"C\" void tc_named_sink(void);\n\n");
    std::vector<bool> has_named(kTestCasesCount, false);
    std::size_t tail_call_sites = 0;
    for (std::size_t i = 0; i < kTestCasesCount; ++i) {
        const TestCase& tc = kTestCases[i];
        armv4t::Instr ins = decode_one(tc);
        const bool direct = ins.op == armv4t::IrOp::B ||
                            ins.op == armv4t::IrOp::BL ||
                            ins.op == armv4t::IrOp::BL_suffix;
        if (!direct || ins.branch_target == 0 || ins.branch_target == tc.pc)
            continue;
        const std::unordered_map<uint64_t, std::string> names = {
            {(static_cast<uint64_t>(ins.branch_target) << 1u) |
                 (tc.thumb ? 1u : 0u),
             "tc_named_sink"},
        };
        armv4t::CodegenCtx ctx{};
        ctx.current_function_addr = tc.pc;
        ctx.current_function_thumb = tc.thumb;
        ctx.alu_immediate_override_pcs = &thumb_alu_immediate_override_pcs;
        ctx.names_by_key = &names;
        bool not_implemented = false;
        std::string body = armv4t::ArmCodegen::emit_instr(
            ins, ctx, &not_implemented);
        if (body.find("tc_named_sink") == std::string::npos) continue;
        for (std::size_t p = body.find("GBARECOMP_TAIL_CALL(");
             p != std::string::npos;
             p = body.find("GBARECOMP_TAIL_CALL(", p + 1)) {
            ++tail_call_sites;
        }
        has_named[i] = true;
        std::fprintf(f,
            "// [%zu] %s (named target 0x%08X)\n"
            "extern \"C\" void tc_named_%zu(void) {\n"
            "%s"
            "    codegen_test_fellthrough();\n"
            "}\n\n",
            i, tc.name, ins.branch_target, i, body.c_str());
    }
    if (tail_call_sites == 0) {
        std::fprintf(stderr,
            "gen_codegen_tests: ERROR — no GBARECOMP_TAIL_CALL sites were "
            "emitted by the named-target variants.\n");
        return 8;
    }
    std::fprintf(f, "extern \"C\" const TestFn kNamedTestFns[] = {\n");
    for (std::size_t i = 0; i < kTestCasesCount; ++i) {
        if (has_named[i]) std::fprintf(f, "    &tc_named_%zu,\n", i);
        else std::fprintf(f, "    nullptr,\n");
    }
    std::fprintf(f, "};\n\n");

    // Lookup table.
    std::fprintf(f,
        "extern \"C\" const TestFn kTestFns[] = {\n");
    for (std::size_t i = 0; i < kTestCasesCount; ++i) {
        std::fprintf(f, "    &tc_%zu,\n", i);
    }
    std::fprintf(f,
        "};\n"
        "extern \"C\" const unsigned kTestFnsCount = %zuu;\n",
        kTestCasesCount);

    if (guarded_trace_sites == 0) {
        std::fprintf(stderr,
            "gen_codegen_tests: ERROR — no guarded runtime_trace_event sites "
            "were emitted; the trace fast-path test lost coverage.\n");
        return 5;
    }

    if (tail_transfer_sites == 0) {
        std::fprintf(stderr,
            "gen_codegen_tests: ERROR — no GBARECOMP_TAIL_* transfers were "
            "emitted; the tail-call shape test lost coverage.\n");
        return 7;
    }

    std::fprintf(stderr,
        "gen_codegen_tests: emitted %zu test functions with %zu guarded trace "
        "sites and %zu tail transfers to %s\n",
        kTestCasesCount, guarded_trace_sites, tail_transfer_sites, out_path);
    return 0;
}

}  // namespace

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: gen_codegen_tests <output.cpp>\n");
        return 2;
    }
    const char* out_path = argv[1];
    FILE* f = std::fopen(out_path, "wb");
    if (!f) {
        std::fprintf(stderr, "gen_codegen_tests: cannot open %s\n", out_path);
        return 3;
    }
    int rc = emit(f, out_path);
    std::fclose(f);
    return rc;
}
