// gen_codegen_tests — build-time generator. Reads the L1 test
// corpus (test_cases.cpp) and emits one recompiled C function per
// case into generated/test_funcs.cpp, alongside the kTestFns lookup
// table. The runner then links the result and runs each function.
//
// Usage:  gen_codegen_tests <output.cpp>
//
// The emitted file is a normal translation unit that:
//   - #includes runtime_arm.h (g_cpu, bus_*, arm_*)
//   - declares one `static void tc_<idx>(void)` per case
//   - defines them with bodies produced by ArmCodegen::emit_instr
//   - exposes `const TestFn kTestFns[]` + `const unsigned kTestFnsCount`
//
// Per PRINCIPLES.md "Interpreter is informative, never load-bearing":
// the generator never calls the interpreter. It calls ArmCodegen
// directly, the same way tools/gba_recompile does.

#include "test_cases.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <unordered_set>

#include "arm_codegen.h"
#include "arm_decode.h"
#include "arm_ir.h"
#include "thumb_decode.h"

namespace {

armv4t::Instr decode_one(const TestCase& tc) {
    if (tc.thumb) {
        return armv4t::ThumbDecoder::decode(
            static_cast<uint16_t>(tc.word & 0xFFFFu), tc.pc);
    }
    return armv4t::ArmDecoder::decode(tc.word, tc.pc);
}

int emit(FILE* f, const char* out_path) {
    const std::unordered_set<uint32_t> thumb_alu_immediate_override_pcs = {
        0x0800E2D2u,
        0x0800E31Cu,
    };
    std::fprintf(f,
        "// generated by gen_codegen_tests — DO NOT EDIT.\n"
        "//\n"
        "// One C function per L1 test case. Each body is what\n"
        "// ArmCodegen::emit_instr produced for that case's decoded\n"
        "// IR. The runner invokes these alongside Interpreter::step\n"
        "// and diffs the resulting state.\n"
        "\n"
        "#include \"runtime_arm.h\"\n"
        "#include \"test_cases.h\"\n"
        "\n");

    // Per-test function bodies.
    for (std::size_t i = 0; i < kTestCasesCount; ++i) {
        const TestCase& tc = kTestCases[i];
        armv4t::Instr ins = decode_one(tc);
        armv4t::CodegenCtx ctx{};
        ctx.current_function_addr = tc.pc;
        ctx.thumb_alu_immediate_override_pcs =
            &thumb_alu_immediate_override_pcs;
        bool not_implemented = false;
        std::string body = armv4t::ArmCodegen::emit_instr(
            ins, ctx, &not_implemented);

        std::fprintf(f,
            "// [%zu] %s (%s) pc=0x%08X word=0x%08X%s\n"
            "extern \"C\" void tc_%zu(void) {\n"
            "%s"
            "}\n\n",
            i, tc.name, tc.thumb ? "THUMB" : "ARM",
            tc.pc, tc.word,
            not_implemented ? "  <not implemented!>" : "",
            i, body.c_str());

        if (not_implemented) {
            std::fprintf(stderr,
                "gen_codegen_tests: WARNING — case %zu (%s) decoded to "
                "an unimplemented IrOp shape. The runner will abort on "
                "runtime_unimplemented_op when this test runs.\n",
                i, tc.name);
        }
    }

    // Lookup table.
    std::fprintf(f,
        "extern \"C\" const TestFn kTestFns[] = {\n");
    for (std::size_t i = 0; i < kTestCasesCount; ++i) {
        std::fprintf(f, "    &tc_%zu,\n", i);
    }
    std::fprintf(f,
        "};\n"
        "extern \"C\" const unsigned kTestFnsCount = %zuu;\n",
        kTestCasesCount);

    std::fprintf(stderr,
        "gen_codegen_tests: emitted %zu test functions to %s\n",
        kTestCasesCount, out_path);
    return 0;
}

}  // namespace

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: gen_codegen_tests <output.cpp>\n");
        return 2;
    }
    const char* out_path = argv[1];
    FILE* f = std::fopen(out_path, "wb");
    if (!f) {
        std::fprintf(stderr, "gen_codegen_tests: cannot open %s\n", out_path);
        return 3;
    }
    int rc = emit(f, out_path);
    std::fclose(f);
    return rc;
}
