option(GBARECOMP_NETPLAY "Build experimental whole-session recomp-net adapter" OFF)
if(NOT GBARECOMP_NETPLAY)
    return()
endif()
foreach(dependency recomp-net rbengine)
    if(NOT EXISTS "${PROJECT_SOURCE_DIR}/external/${dependency}/CMakeLists.txt")
        message(FATAL_ERROR "GBARECOMP_NETPLAY needs: git submodule update --init external/${dependency}")
    endif()
endforeach()
set(RNET_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(RNET_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(RBE_BUILD_TESTS OFF CACHE BOOL "" FORCE)
if(NOT TARGET recomp_net)
    add_subdirectory(external/recomp-net EXCLUDE_FROM_ALL)
endif()
if(NOT TARGET retcomm_rbengine)
    add_subdirectory(external/rbengine EXCLUDE_FROM_ALL)
endif()
add_library(gbarecomp_netplay STATIC src/runtime/multiplayer_netplay.cpp src/runtime/multiplayer_startup.cpp)
target_include_directories(gbarecomp_netplay PUBLIC src/runtime src/armv4t src/gba)
target_link_libraries(gbarecomp_netplay PUBLIC gbarecomp_runtime recomp_net retcomm_rbengine)
add_gbarecomp_runtime_stack_test(multiplayer_netplay_tests tests/link/netplay_test.cpp)
target_link_libraries(multiplayer_netplay_tests PRIVATE gbarecomp_netplay)
add_executable(multiplayer_netplay_peer tests/link/netplay_peer.cpp tools/bios_smoke/dispatch_stub.cpp)
target_link_gbarecomp_runtime_stack(multiplayer_netplay_peer)
target_link_libraries(multiplayer_netplay_peer PRIVATE gbarecomp_netplay)
find_package(Python3 COMPONENTS Interpreter QUIET)
if(Python3_Interpreter_FOUND)
    foreach(mode delay rollback)
        if(mode STREQUAL "rollback")
            set(use_rollback 1)
        else()
            set(use_rollback 0)
        endif()
        add_test(NAME multiplayer_${mode}_loopback COMMAND ${Python3_EXECUTABLE}
            ${PROJECT_SOURCE_DIR}/tests/link/loopback.py $<TARGET_FILE:multiplayer_netplay_peer> ${use_rollback})
        set_tests_properties(multiplayer_${mode}_loopback PROPERTIES TIMEOUT 120)
    endforeach()
    foreach(scenario loss mismatch)
        add_test(NAME multiplayer_${scenario}_loopback COMMAND ${Python3_EXECUTABLE}
            ${PROJECT_SOURCE_DIR}/tests/link/loopback.py $<TARGET_FILE:multiplayer_netplay_peer> 1 ${scenario})
        set_tests_properties(multiplayer_${scenario}_loopback PROPERTIES TIMEOUT 120)
    endforeach()
endif()
