option(GBARECOMP_NETPLAY "Build experimental whole-session recomp-net adapter" OFF)
if(NOT GBARECOMP_NETPLAY)
    return()
endif()
include(${CMAKE_CURRENT_LIST_DIR}/GbaNetplayIdentity.cmake)
# Explicitly built qualification tool: uses the game's real generated code
# and render callbacks, with user-supplied local assets/warm session state.
function(gbarecomp_target_netplay_view_probe target adapter)
    get_target_property(sources ${target} SOURCES)
    list(FILTER sources EXCLUDE REGEX "(^|/)main\\.cpp$")
    set(probe ${target}ViewProbe)
    add_executable(${probe} EXCLUDE_FROM_ALL ${sources} ${adapter}
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/link/view_game_probe.cpp")
    get_target_property(includes ${target} INCLUDE_DIRECTORIES)
    get_target_property(defines ${target} COMPILE_DEFINITIONS)
    get_target_property(libraries ${target} LINK_LIBRARIES)
    target_include_directories(${probe} PRIVATE ${includes})
    target_compile_definitions(${probe} PRIVATE ${defines})
    list(FILTER libraries EXCLUDE REGEX "^-Wl,--(start|end)-group$")
    target_link_gbarecomp_runtime_stack(${probe} ${libraries} gbarecomp_netplay)
endfunction()
function(gbarecomp_target_netplay_launcher target)
    if(NOT COMMAND recomp_target_launcher_netplay)
        message(FATAL_ERROR "Netplay requires recomp-ui with the shared netplay backend")
    endif()
    recomp_target_launcher_netplay(${target})
    target_link_libraries(${target} PRIVATE gbarecomp_netplay)
    if(NOT TARGET multiplayer_launcher_seam_tests)
        set(engine_root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/..")
        add_executable(multiplayer_launcher_seam_tests
            "${engine_root}/tests/link/launcher_seam_test.cpp"
            "${engine_root}/tools/bios_smoke/dispatch_stub.cpp")
        target_link_gbarecomp_runtime_stack(multiplayer_launcher_seam_tests
            gbarecomp_netplay recomp_launcher_netplay ${target})
        add_test(NAME multiplayer_launcher_seam_tests COMMAND multiplayer_launcher_seam_tests)
    endif()
endfunction()
foreach(dependency recomp-net rbengine)
    if(NOT EXISTS "${PROJECT_SOURCE_DIR}/external/${dependency}/CMakeLists.txt")
        message(FATAL_ERROR "GBARECOMP_NETPLAY needs: git submodule update --init external/${dependency}")
    endif()
endforeach()
set(RNET_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(RNET_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(RBE_BUILD_TESTS OFF CACHE BOOL "" FORCE)
if(NOT TARGET recomp_net)
    add_subdirectory(external/recomp-net EXCLUDE_FROM_ALL)
endif()
if(NOT TARGET retcomm_rbengine)
    add_subdirectory(external/rbengine EXCLUDE_FROM_ALL)
endif()
add_library(gbarecomp_netplay STATIC src/runtime/multiplayer_netplay.cpp src/runtime/multiplayer_startup.cpp
    src/runtime/multiplayer_checkpoint.cpp src/runtime/multiplayer_checkpoint_file.cpp
    src/runtime/multiplayer_match.cpp src/runtime/multiplayer_pacing.cpp
    src/runtime/multiplayer_launch.cpp src/runtime/multiplayer_runner.cpp
    src/runtime/multiplayer_view.cpp)
target_include_directories(gbarecomp_netplay PUBLIC src/runtime src/armv4t src/gba)
target_link_libraries(gbarecomp_netplay PUBLIC gbarecomp_runtime recomp_net retcomm_rbengine)
if(TARGET gba_link_probe)
    target_sources(gba_link_probe PRIVATE tools/link_session/netplay_probe.cpp)
    target_compile_definitions(gba_link_probe PRIVATE GBA_LINK_PROBE_NETPLAY=1)
    target_link_libraries(gba_link_probe PRIVATE gbarecomp_netplay)
endif()
add_gbarecomp_runtime_stack_test(multiplayer_netplay_tests tests/link/netplay_test.cpp)
target_link_libraries(multiplayer_netplay_tests PRIVATE gbarecomp_netplay)
add_executable(multiplayer_launch_tests tests/link/launch_test.cpp tools/bios_smoke/dispatch_stub.cpp)
target_link_gbarecomp_runtime_stack(multiplayer_launch_tests gbarecomp_netplay)
add_test(NAME multiplayer_launch_tests COMMAND multiplayer_launch_tests)
add_executable(multiplayer_view_tests tests/link/view_test.cpp tools/bios_smoke/dispatch_stub.cpp)
target_link_gbarecomp_runtime_stack(multiplayer_view_tests gbarecomp_netplay)
add_test(NAME multiplayer_view_tests COMMAND multiplayer_view_tests)
add_executable(multiplayer_netplay_peer tests/link/netplay_peer.cpp tools/bios_smoke/dispatch_stub.cpp)
target_link_gbarecomp_runtime_stack(multiplayer_netplay_peer)
target_link_libraries(multiplayer_netplay_peer PRIVATE gbarecomp_netplay)
add_executable(multiplayer_match_peer tests/link/match_peer.cpp tools/bios_smoke/dispatch_stub.cpp)
target_link_gbarecomp_runtime_stack(multiplayer_match_peer)
target_link_libraries(multiplayer_match_peer PRIVATE gbarecomp_netplay)
find_package(Python3 COMPONENTS Interpreter QUIET)
if(Python3_Interpreter_FOUND)
    foreach(mode delay rollback)
        if(mode STREQUAL "rollback")
            set(use_rollback 1)
        else()
            set(use_rollback 0)
        endif()
        add_test(NAME multiplayer_${mode}_loopback COMMAND ${Python3_EXECUTABLE}
            ${PROJECT_SOURCE_DIR}/tests/link/loopback.py $<TARGET_FILE:multiplayer_netplay_peer> ${use_rollback})
        set_tests_properties(multiplayer_${mode}_loopback PROPERTIES TIMEOUT 120)
    endforeach()
    foreach(scenario loss mismatch outage startup_loss checkpoint_mismatch restart)
        set(use_rollback 1)
        if(scenario STREQUAL "checkpoint_mismatch")
            set(use_rollback 0)
        endif()
        add_test(NAME multiplayer_${scenario}_loopback COMMAND ${Python3_EXECUTABLE}
            ${PROJECT_SOURCE_DIR}/tests/link/loopback.py $<TARGET_FILE:multiplayer_netplay_peer> ${use_rollback} ${scenario})
        set_tests_properties(multiplayer_${scenario}_loopback PROPERTIES TIMEOUT 120)
    endforeach()
    foreach(scenario delay rollback mismatch policy_mismatch outage startup_loss restart request_checkpoint request_delay request_outage checkpoint_skew)
        set(use_rollback 1)
        set(relay_scenario ${scenario})
        if(scenario STREQUAL "delay")
            set(use_rollback 0)
            set(relay_scenario ordinary)
        elseif(scenario STREQUAL "rollback")
            set(relay_scenario ordinary)
        elseif(scenario STREQUAL "request_delay")
            set(use_rollback 0)
            set(relay_scenario request_checkpoint)
        elseif(scenario STREQUAL "checkpoint_skew")
            set(use_rollback 0)
        endif()
        add_test(NAME multiplayer_match_${scenario} COMMAND ${Python3_EXECUTABLE}
            ${PROJECT_SOURCE_DIR}/tests/link/loopback.py $<TARGET_FILE:multiplayer_match_peer> ${use_rollback} ${relay_scenario})
        set_tests_properties(multiplayer_match_${scenario} PROPERTIES TIMEOUT 120)
    endforeach()
endif()
